### ISSUE TITLE
최신의 가이드가 아니다.

### ISSUE THREAD

**Issue by dalzony** [kwakbab/clojure-style-guide#1]
https://github.com/kwakbab/clojure-style-guide/tree/6ae31bf68382fcfabb99d081c1d810821333c0ff 

위 문서를 기준으로 번역했기 때문에, 최신의 가이드로 수정해야합니다.

**Comment by eunmin** [comment]
네이밍 빠진 부분 번역해서 풀리퀘 날렸습니다.

**Comment by eunmin** [comment]
업데이트 했습니다.
